## ML Lab Assessment

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Data

In [6]:
data = pd.read_csv("USA_Housing.csv")

About Data

Data from : https://www.kaggle.com/dmvreddy91/usahousing

In [7]:
data

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0         79545.458574             5.682861                   7.009188   
1         79248.642455             6.002900                   6.730821   
2         61287.067179             5.865890                   8.512727   
3         63345.240046             7.188236                   5.586729   
4         59982.197226             5.040555                   7.839388   
...                ...                  ...                        ...   
4995      60567.944140             7.830362                   6.137356   
4996      78491.275435             6.999135                   6.576763   
4997      63390.686886             7.250591                   4.805081   
4998      68001.331235             5.534388                   7.130144   
4999      65510.581804             5.992305                   6.792336   

      Avg. Area Number of Bedrooms  Area Population         Price  \
0                             4.09     23086.800503  1.059034e+06   
1                             3.09     40173.072174  1.505891e+06   
2                             5.13     36882.159400  1.058988e+06   
3                             3.26     34310.242831  1.260617e+06   
4                             4.23     26354.109472  6.309435e+05   
...                            ...              ...           ...   
4995                          3.46     22837.361035  1.060194e+06   
4996                          4.02     25616.115489  1.482618e+06   
4997                          2.13     33266.145490  1.030730e+06   
4998                          5.44     42625.620156  1.198657e+06   
4999                          4.07     46501.283803  1.298950e+06   

                                                Address  
0     208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1     188 Johnson Views Suite 079\nLake Kathleen, CA...  
2     9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                             USS Barnett\nFPO AP 44820  
4                            USNS Raymond\nFPO AE 09386  
...                                                 ...  
4995                   USNS Williams\nFPO AP 30153-7653  
4996              PSC 9258, Box 8489\nAPO AA 42991-3352  
4997  4215 Tracy Garden Suite 076\nJoshualand, VA 01...  
4998                          USS Wallace\nFPO AE 73316  
4999  37778 George Ridges Apt. 509\nEast Holly, NV 2...  

[5000 rows x 7 columns]

In [8]:
import seaborn as sb
sb.pairplot(data)

# Simple Linear Regression

In [9]:
x = data.iloc[:,0]

In [10]:
y = data.iloc[:,5]

In [11]:
x

0       79545.458574
1       79248.642455
2       61287.067179
3       63345.240046
4       59982.197226
            ...     
4995    60567.944140
4996    78491.275435
4997    63390.686886
4998    68001.331235
4999    65510.581804
Name: Avg. Area Income, Length: 5000, dtype: float64

In [12]:
y

0       1.059034e+06
1       1.505891e+06
2       1.058988e+06
3       1.260617e+06
4       6.309435e+05
            ...     
4995    1.060194e+06
4996    1.482618e+06
4997    1.030730e+06
4998    1.198657e+06
4999    1.298950e+06
Name: Price, Length: 5000, dtype: float64

In [13]:
r = np.corrcoef(x, y)

In [14]:
r

array([[1.        , 0.63973378],
       [0.63973378, 1.        ]])

In [15]:
sb.heatmap(r)

<AxesSubplot:>

In [16]:
sumxy = 0
sumx = 0
sumy = 0
sumxsq = 0
for i in range(0,len(x)):
    sumxy = sumxy + x[i]*y[i]
    sumx = sumx + x[i]
    sumy = sumy + y[i]
    sumxsq = sumxsq + (x[i]*x[i])

In [17]:
N = len(x)

In [18]:
w1 = (sumxy) - ((sumx*sumy)/N)

In [19]:
w1 = w1/((sumxsq) - ((sumx*sumx)/N))

In [20]:
w1

21.195483171932057

In [21]:
w0 = (sumy/N) - w1*(sumx/N)

In [22]:
w0

-221579.47820594045

In [23]:
x = np.array(x)

In [24]:
y = np.array(y)

In [25]:
y1 = w0 + w1 * x
plt.plot(x,y1,label="Regression Line")
plt.scatter(x, y, label='data points')

# Multi Linear Regression (Using Normal Equations)

In [26]:
x = data.iloc[:,0:5]

In [27]:
y = data.iloc[:,5]

In [28]:
an_array = np.full((len(y), 1), 1)    

In [29]:
an_array

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])

In [30]:
x = np.append(x, an_array, axis=1)

In [31]:
x = np.array(x)

In [32]:
y = np.array(y)

In [33]:
sb.heatmap(data.corr())

<AxesSubplot:>

In [34]:
np.shape(x)

(5000, 6)

In [35]:
r = y

Calculating Design Matrix

Using y as the design matrix, taking hypothesis as w1x0+w2x1+x3x2+w4x3+w5x4+w0 = y

Formula = inverse (dT * d) *  (dT*r)

Where dT is the transpose of the design matrix and r is the outcome/predicted value

In [36]:
d = x
dT = np.transpose(d)

In [37]:
weights = np.matmul(np.linalg.inv(np.matmul(dT,d)),np.matmul(dT,r))

In [38]:
weights

array([ 2.15780494e+01,  1.65637027e+05,  1.20659949e+05,  1.65113905e+03,
        1.52007439e+01, -2.63729903e+06])

In [39]:
w1 = weights[0]
w2 = weights[1]
w3 = weights[2]
w4 = weights[3]
w5 = weights[4]
w0 = weights[5]
np.shape(x)

(5000, 6)

In [40]:
predY = np.empty(len(y))
for i in range(0,len(y)):
    predY[i] = w1*x[i,0] + w2*x[i,1] + w3*x[i,2] + w4*x[i,3] + w5*x[i,4] + w0

In [48]:
totdiff = 0
for i in range(0,len(y)):
    totdiff = totdiff + (predY[i] - y[i])

In [49]:
totdiff/len(y)

-4.107481800019741e-09

# Decision Tree

In [44]:
from sklearn import linear_model
from sklearn import metrics
regression = linear_model.LinearRegression()
d = data.values
train_x = (d[:,0:5])
train_y = d[:,5]
regression.fit(train_x, train_y)
y_predicted = regression.predict(train_x)

In [46]:
totdiff = 0
for i in range(0,len(train_y)):
    totdiff = totdiff + (y_predicted[i] - train_y[i])
print(totdiff/len(y))

6.139744073152542e-11
